---
# Install MapR Pre-requisites software packages

  - name: Install libselinux-python tools
    yum: name=libselinux-python state=present

  - name: Set selinux config to permissive
    selinux: state=permissive policy=targeted
    when: ansible_distribution not in ('Amazon')

  - name: Selinux to permissive now
    command: setenforce permissive
    when: ansible_distribution not in ('Amazon')

  - name: Install redhat-lsb-core
    yum: name=redhat-lsb-core state=present

  - name: Reread ansible_lsb facts
    setup: filter=ansible_lsb*

  - name: Disable iptables
    service: name=iptables state=stopped enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    when: ansible_lsb.major_release|int == 6

  - name: Disable firewalld
    service: name=firewalld state=stopped enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    when: ansible_lsb.major_release|int == 7

#  - name: Install EPEL
#    yum: name=epel-release state=installed

  - name: Install EPEL on CentOS v6.x
    yum: name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=installed
    when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int == 6

  - name: Install EPEL on CentOS v7.x
    yum: name=http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=installed
    when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int == 7

  - name: Install NTP
    yum: name=ntp state=present

  - name: Restart NTP
    service: state=restarted name=ntpd

  - name: Ensure NTP is enabled
    service: name=ntpd enabled=yes state=started

  - name: Install nfs-utils to get rpcbind
    yum: name=nfs-utils state=installed

  - name: Ensure linux NFS services are disabled
    service: name={{item}} state=stopped enabled=no
    with_items:
      - nfs
      - nfslock

  - name: Ensure rpcbind starts
    service: name=rpcbind state=started enabled=yes

  - name: Ensure TCP retries are set to 5
    lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_retries2" line="net.ipv4.tcp_retries2=5"
#    notify: reload sysctl

  - name: Disable memory overcommit
    lineinfile: dest=/etc/sysctl.conf regexp="^vm.overcommit_memory" line="vm.overcommit_memory=0"
#    notify: reload sysctl
